#!/bin/bash

set -e

if [[ $(uname -s) == 'Darwin' ]]
then
	CONFIG="mac.yaml"
else
	CONFIG="linux.yaml"
fi

DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
#git submodule update --init --recursive "${DOTBOT_DIR}"
git submodule update --init --recursive

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "install.d/${CONFIG}" "${@}"
