# Taps
tap 'caskroom/cask'
tap 'caskroom/fonts'
tap 'homebrew/bundle'

# Install GNU core utilities (those that come with macOS are outdated)
brew 'coreutils'
brew 'moreutils'
brew 'findutils'

# Dev
#brew 'python'
brew 'python3'
brew 'ruby'
brew 'node'
#brew 'yarn'
#brew 'flake8'

# Install Binaries
brew 'wget'
brew 'git'
brew 'vim'
brew 'tmux'
brew 'hub'
brew 'tree'
#brew 'mackup'

# Install ZSH
brew 'zsh'
brew 'zsh-completions'
brew 'zsh-syntax-highlighting'
brew 'antigen'

# Apps
#cask 'iterm2'
#cask 'atom'
#cask 'dropbox'
#cask 'firefox'
#cask 'google-chrome'
#cask 'google-drive'
#cask 'handbrake'
#cask 'spotify'
#cask 'transmission'
#cask 'vlc'
#cask 'teamviewer'

# Fonts
cask 'font-roboto-mono'
cask 'font-roboto-mono-for-powerline'

