[env]
TERM = "xterm-256color"

[window]
blur            = true
decorations     = "buttonless"
opacity         = 0.85
option_as_alt   = "both"

[window.padding]
x = 10
y = 10

[font]
size = 12

[font.normal]
family = "MesloLGS NF"

# Theme
import = [ "~/.config/alacritty/themes/one_dark.toml" ]

