#
# Theme settings
#

# Fall back mode for powerlevel9k when SSH-ing to server with 'dotfiles' repo and
# powerlevel9k installed, but 'dotfiles' repo and fonts not available on client.
if [ -z $SSH_CLIENT ]; then
    # this env variable will be available only if this .zshrc is used on client
    export LC_CLIENT_HAS_DOT_FILE_REPO=1
    POWERLEVEL9K_MODE='nerdfont-complete'
fi
if [ -z $LC_CLIENT_HAS_DOT_FILE_REPO ]; then
    POWERLEVEL9K_MODE='default'
fi

# OMZ-Theme powerlevel9k settings
DEFAULT_USER=$USER
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(context dir vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status background_jobs ram load)
POWERLEVEL9K_SHORTEN_DIR_LENGTH=1
POWERLEVEL9K_SHORTEN_DELIMITER=""
POWERLEVEL9K_SHORTEN_STRATEGY="truncate_from_right"
POWERLEVEL9K_CONTEXT_REMOTE_BACKGROUND='132'
POWERLEVEL9K_CONTEXT_REMOTE_FOREGROUND='235'
POWERLEVEL9K_DIR_HOME_BACKGROUND='24'
POWERLEVEL9K_DIR_HOME_FOREGROUND='250'
POWERLEVEL9K_DIR_HOME_SUBFOLDER_BACKGROUND='109'
POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND='235'
POWERLEVEL9K_DIR_DEFAULT_BACKGROUND='66'
POWERLEVEL9K_DIR_DEFAULT_FOREGROUND='235'
POWERLEVEL9K_VCS_CLEAN_BACKGROUND='142'
POWERLEVEL9K_VCS_CLEAN_FOREGROUND='236'
POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND='167'
POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND='236'
POWERLEVEL9K_VCS_MODIFIED_BACKGROUND='214'
POWERLEVEL9K_VCS_MODIFIED_FOREGROUND='236'
POWERLEVEL9K_RAM_ELEMENTS="ram-free"
POWERLEVEL9K_RAM_BACKGROUND='208'
POWERLEVEL9K_LOAD_NORMAL_BACKGROUND='72'
POWERLEVEL9K_LOAD_WARNING_BACKGROUND='172'
POWERLEVEL9K_LOAD_CRITICAL_BACKGROUND='124'
POWERLEVEL9K_INSTALLATION_PATH=$ANTIGEN_BUNDLES/bhilburn/powerlevel9k/powerlevel9k.zsh-theme

#
# Load default theme
#
antigen theme bhilburn/powerlevel9k powerlevel9k
#antigen theme nojhan/liquidprompt

