unalias run-help
autoload run-help
HELPDIR=/usr/local/share/zsh/help

# Enable ZSH Completions
fpath=(/usr/local/share/zsh-completions $fpath)

# Enable syntax highlightning
source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# Uncomment the following line to use case-sensitive completion.
CASE_SENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment to enable automatic upgrades
DISABLE_UPDATE_PROMPT=true

# Uncomment the following line to change how often to auto-update (in days).
export UPDATE_ZSH_DAYS=7

# Uncomment the following line to enable command auto-correction.
ENABLE_CORRECTION="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
HIST_STAMPS="dd/mm/yyyy"

# You may need to manually set your language environment
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
  export EDITOR='mvim'
fi

# Activate Oh-My-Zsh
#source $ZSH/oh-my-zsh.sh

# Which plugins would you like to load? (plugins can be found in $ZSH/plugins/*)
# Custom plugins may be added to $ZSH/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
#plugins=(osx brew git git-extras npm pip python rbenv)

# OMZ-Theme powerlevel9k settings
#DEFAULT_USER=bassa
#POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(context dir background_jobs)
#POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status vcs ram)
#POWERLEVEL9K_DIR_DEFAULT_BACKGROUND='033'

# Set name of the theme to load.
# Look in $ZSH/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
#ZSH_THEME="powerlevel9k/powerlevel9k"

# Enable Powerline
#. /usr/local/lib/python3.5/site-packages/powerline/bindings/zsh/powerline.zsh

# Activate Antigen
source /usr/local/share/antigen/antigen.zsh

# Load the oh-my-zsh's library.
antigen use oh-my-zsh

# Bundles from the default repo (robbyrussell's oh-my-zsh).
antigen bundle osx
antigen bundle tmux
antigen bundle git
antigen bundle git-extras
antigen bundle python
antigen bundle pip
antigen bundle npm
antigen bundle rbenv
antigen bundle gem
antigen bundle rails
antigen bundle heroku
antigen bundle docker

# Syntax highlighting bundle.
antigen bundle zsh-users/zsh-syntax-highlighting

# Load the theme.
antigen theme powerlevel9k

# Tell antigen that you're done.
antigen apply

