[audio]
sound_volume = 0.85

[backdrop]
blur_intensity = 0.25
tint_intensity = 0.0

[bar.default]
background_opacity = 0.5
capsule_opacity = 0.65
capsule_thickness = 0.75
center = [ "active_window" ]
end = [ "group:g1", "privacy", "clipboard", "notifications", "clock", "launcher", "control-center", "session" ]
margin_edge = 12
margin_ends = 12
padding = 12
start = [ "workspaces" ]

    [bar.default.monitor.HDMI-A-1]
    center = [ "media" ]
    end = [ "group:g1" ]
    scale = 0.9
    start = [ "workspaces" ]
    thickness = 28

        [[bar.default.monitor.HDMI-A-1.capsule_group]]
        accordion = false
        accordion_direction = "end"
        enabled = true
        fill = "surface_variant"
        id = "g1"
        members = [ "temp", "cpu", "ram", "sysmon", "network_rx", "network_tx" ]
        opacity = 0.65
        padding = 6.0

    [[bar.default.capsule_group]]
    accordion = false
    accordion_direction = "end"
    enabled = true
    fill = "surface_variant"
    id = "g1"
    members = [ "tray", "bar" ]
    opacity = 0.65
    padding = 6.0

[brightness]
enable_ddcutil = true
minimum_brightness = 0.05
sync_all_monitors = true

[control_center]
hidden_tabs = [ "media", "calendar", "notifications", "screen-time" ]
sidebar = "full"
sidebar_section = "full"

    [[control_center.shortcuts]]
    type = "dark_mode"

    [[control_center.shortcuts]]
    type = "nightlight"

    [[control_center.shortcuts]]
    type = "audio"

    [[control_center.shortcuts]]
    type = "mic_mute"

[desktop_widgets]
enabled = false

[hooks]
session_locked = "1password --lock"
session_unlocked = "1password --quick-access"
started = "1password --silent"

[idle]
behavior_order = [ "lock", "screen-off", "lock-and-suspend" ]

    [idle.behavior.lock]
    action = "lock"
    enabled = true
    timeout = 300.0

    [idle.behavior.lock-and-suspend]
    action = "suspend"
    enabled = true
    lock_before_suspend = false
    timeout = 900.0

    [idle.behavior.screen-off]
    action = "screen_off"
    enabled = true
    timeout = 600.0

[location]
address = "Alessandria, IT"

[lockscreen]
fingerprint = false
monitors = []

[lockscreen_widgets]
enabled = true
schema_version = 2
widget_order = [
    "lockscreen-login-box@HDMI-A-1",
    "lockscreen-login-box@DP-1",
    "lockscreen-widget-0000000000000001",
    "lockscreen-widget-0000000000000002",
    "lockscreen-widget-0000000000000003",
    "lockscreen-widget-0000000000000004",
    "lockscreen-widget-0000000000000005",
    "lockscreen-widget-0000000000000006",
    "lockscreen-widget-0000000000000007",
    "lockscreen-widget-0000000000000008"
]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@DP-1"]
    box_height = 192.0
    box_width = 800.0
    cx = 1280.0
    cy = 608.0
    output = "DP-1"
    placement_height = 1440.0
    placement_width = 2560.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@DP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.5
        background_radius = 12.0
        center_password_text = true
        input_opacity = 1.0
        input_radius = 12.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = false
        show_media = false
        show_session_buttons = true
        show_unlock_hint = false
        show_weather = false

    [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1"]
    box_height = 192.0
    box_width = 800.0
    cx = 540.0
    cy = 1728.0
    enabled = false
    output = "HDMI-A-1"
    placement_height = 1920.0
    placement_width = 1080.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.5
        background_radius = 12.0
        center_password_text = true
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = false
        show_media = false
        show_session_buttons = true
        show_unlock_hint = false
        show_weather = false

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000001]
    box_height = 64.0
    box_width = 800.0
    cx = 1280.0
    cy = 416.0
    output = "DP-1"
    placement_height = 1440.0
    placement_width = 2560.0
    rotation = -0.0
    type = "clock"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000001.settings]
        background = true
        background_opacity = 0.5
        background_padding = 12
        background_radius = 12
        color = "on_surface"
        format = "{:%A%e %B %Y}"

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000002]
    box_height = 160.0
    box_width = 800.0
    cx = 1280.0
    cy = 240.0
    output = "DP-1"
    placement_height = 1440.0
    placement_width = 2560.0
    rotation = -0.0
    type = "clock"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000002.settings]
        background = true
        background_opacity = 0.5
        background_padding = 12
        background_radius = 12
        color = "on_surface"
        format = "{:%H:%M}"

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000003]
    box_height = 160.0
    box_width = 800.0
    cx = 540.0
    cy = 496.0
    output = "HDMI-A-1"
    placement_height = 1920.0
    placement_width = 1080.0
    rotation = 0.0
    type = "sysmon"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000003.settings]
        background = false
        background_opacity = 0.5
        background_padding = 12
        color = "on_primary"
        color2 = "shadow"
        font_family = "JetBrains Mono"
        network_speed_unit = "kb"
        shadow = false
        show_label = true
        stat = "net_rx"
        stat2 = "net_tx"

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000004]
    box_height = 160.0
    box_width = 800.0
    cx = 540.0
    cy = 144.0
    output = "HDMI-A-1"
    placement_height = 1920.0
    placement_width = 1080.0
    rotation = 0.0
    type = "sysmon"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000004.settings]
        background = false
        background_opacity = 0.5
        background_padding = 12
        color = "on_primary"
        color2 = "shadow"
        font_family = "JetBrains Mono"
        shadow = false
        show_label = true
        stat = "cpu_usage"
        stat2 = "ram_pct"

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000005]
    box_height = 160.0
    box_width = 800.0
    cx = 540.0
    cy = 320.0
    output = "HDMI-A-1"
    placement_height = 1920.0
    placement_width = 1080.0
    rotation = 0.0
    type = "sysmon"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000005.settings]
        background = false
        background_opacity = 0.5
        background_padding = 12
        color = "on_primary"
        color2 = "shadow"
        font_family = "JetBrains Mono"
        shadow = false
        show_label = true
        stat = "gpu_usage"
        stat2 = "gpu_vram"

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000006]
    box_height = 256.0
    box_width = 800.0
    cx = 540.0
    cy = 736.0
    output = "HDMI-A-1"
    placement_height = 1920.0
    placement_width = 1080.0
    rotation = 0.0
    type = "media_player"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000006.settings]
        background_opacity = 0.5
        background_padding = 12
        hide_when_no_media = true
        layout = "horizontal"

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000007]
    box_height = 448.0
    box_width = 512.0
    cx = 540.0
    cy = 1120.0
    output = "HDMI-A-1"
    placement_height = 1920.0
    placement_width = 1080.0
    rotation = 0.0
    type = "calendar"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000007.settings]
        background = true
        background_opacity = 0.5
        background_padding = 12
        show_events = false
        show_week_numbers = true

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000008]
    box_height = 512.0
    box_width = 480.0
    cx = 1280.0
    cy = 1024.0
    output = "DP-1"
    placement_height = 1440.0
    placement_width = 2560.0
    rotation = 0.0
    type = "weather"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000008.settings]
        background_opacity = 0.5
        background_padding = 12
        forecast_days = 6
        show_forecast = true

[notification]
background_opacity = 0.65
monitors = [ "DP-1" ]

[osd]
background_opacity = 0.65

    [osd.kinds]
    media = false

[plugins]
enabled = [ "rylos/syncthing" ]

[shell]
avatar_path = "/home/norville/.face"
clipboard_keep_from_closed_apps = false
polkit_agent = true
show_location = false

    [shell.panel]
    control_center_placement = "floating"
    control_center_position = "center"
    session_placement = "floating"
    session_position = "center"
    wallpaper_placement = "floating"

    [shell.screen_corners]
    enabled = true
    size = 12

    [[shell.session.actions]]
    action = "logout"
    countdown_seconds = 10.0
    enabled = true
    shortcut = "1"
    variant = "default"

    [[shell.session.actions]]
    action = "lock"
    countdown_seconds = 10.0
    enabled = true
    shortcut = "2"
    variant = "default"

    [[shell.session.actions]]
    action = "suspend"
    countdown_seconds = 10.0
    enabled = true
    shortcut = "3"
    variant = "default"

    [[shell.session.actions]]
    action = "reboot"
    countdown_seconds = 10.0
    enabled = true
    shortcut = "4"
    variant = "default"

    [[shell.session.actions]]
    action = "shutdown"
    countdown_seconds = 10.0
    enabled = true
    shortcut = "5"
    variant = "destructive"

[theme]
builtin = "Tokyo-Night"
custom_palette = "tokyonight_moon"
mode = "auto"
source = "custom"

    [theme.templates]
    enable_builtin_templates = false
    enable_community_templates = false

[wallpaper.default]
path = "/home/norville/Pictures/Wallpapers/primary.jpg"

[wallpaper.last]
path = "/home/norville/Pictures/Wallpapers/secondary.jpg"

[wallpaper.monitors.DP-1]
path = "/home/norville/Pictures/Wallpapers/primary.jpg"

[wallpaper.monitors.HDMI-A-1]
path = "/home/norville/Pictures/Wallpapers/secondary.jpg"

[widget.active_window]
capsule = true
capsule_opacity = 0.65
max_length = 800

[widget.bar]
type = "rylos/syncthing:bar"

[widget.clock]
capsule = true
capsule_opacity = 0.65
font_family = "JetBrains Mono"
format = "%a•%d %H:%M"

[widget.cpu]
font_family = "JetBrains Mono"
show_value = false
visualization = "gauge"

[widget.launcher]
custom_image = "/usr/share/icons/cachyos.svg"
custom_image_colorize = true

[widget.media]
capsule = true
capsule_opacity = 0.65
hide_when_no_media = true
max_length = 600

[widget.network]
show_label = false

[widget.network_rx]
font_family = "JetBrains Mono"
network_speed_compact = true
show_value = false
visualization = "gauge"

[widget.network_tx]
font_family = "JetBrains Mono"
network_speed_compact = true
show_value = false
visualization = "gauge"

[widget.notifications]
hide_when_no_unread = false

[widget.privacy]
active_color = "error"
hide_inactive = false
icon_spacing = 6
inactive_color = "primary"

[widget.ram]
font_family = "JetBrains Mono"
show_value = false
visualization = "gauge"

[widget.session]
color = "error"

[widget.sysmon]
font_family = "JetBrains Mono"
show_value = false
stat = "disk_used_pct"
visualization = "gauge"

[widget.temp]
font_family = "JetBrains Mono"
show_value = false
visualization = "gauge"

[widget.tray]
capsule_opacity = 0.65

[widget.workspaces]
capsule = true
capsule_opacity = 0.65
empty_color = "shadow"
focused_output_only = true
font_weight = 700
labels_only_when_occupied = true
